name: Rearc Quest CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' 
      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
      - name: Compile Project
        run: sbt compile
      - name: Run tests
        run: sbt test